version: "3.7"

services:
  caddy:
    image: caddy:2.4.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./.docker/caddy/static.Caddyfile:/etc/caddy/static.Caddyfile
      - ./frontend/build:/opt/frontend/build
  
  frontend:
    image: maxkaemmerer/docker-elm:1.0.0
    restart: unless-stopped
    volumes:
      - ./frontend:/opt/app