name: Code Quality CI

on:
  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@v2
    - run: make install
    - run: make test
    - run: make validate-format
    - run: make build
